services:
  - type: web
    name: automaticus
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn automaticus:app
    envVars:
      - key: PORT
        value: 10000
